---
- name: Configuring banner on Cisco IOS Devices
  gather_facts: no
  hosts: routers
  connection: network_cli

    tasks:
    - name: Configure banner
      ios_banner:
        banner: login
        txt: |
          *******************************************************************************
          *                                                                             *
          *                   Welcome to Cisco IOS_Ansible Automation                   *
          *                                                                             *
          *  Unauthorized access to this system is strictly prohibited. By accessing    *
          *  this system, you agree to comply with all applicable policies and          *
          *  regulations. Any violation may result in legal action.                     *
          *                                                                             *
          *******************************************************************************
        state: present
         register: output

    - name: Printing at the console
      debug: var=output
...
